export const UPDATE_FUNDRAISER = "UPDATE_FUNDRAISER";
export const LOGIN_USER = "LOGIN_USER";
export const CREATE_USER = "CREATE_USER";
export const CREATE_FUNDRAISER = "CREATE_FUNDRAISER";
export const DELETE_FUNDRAISER = "DELETE_FUNDRAISER";
export const QUERY_FUNDRAISER = "QUERY_FUNDRAISER";
export const QUERY_USER = "QUERY_USER";